package com.example.razryadapi

data class Author(
    val nickname: String,
    val tableNumber: Int,
    val commission: Boolean,
    val swap: Boolean,
    val interactiveQuest: Boolean,
    val moneyQuest: Boolean
)
fun main() {
    val authors = listOf(
        Author("iris", 2, commission = false, swap = true, interactiveQuest = true, moneyQuest = true),
        Author("Demi", 2, commission = false, swap = true, interactiveQuest = false, moneyQuest = true),
        Author("BRIT/0.5", 3, commission = false, swap = true, interactiveQuest = false, moneyQuest = true),
        Author("Gosuto", 3, commission = true, swap = true, interactiveQuest = false, moneyQuest = true),
        Author("vhka", 4, commission = false, swap = true, interactiveQuest = true, moneyQuest = true),
        Author("mag", 4, commission = false, swap = false, interactiveQuest = false, moneyQuest = true),
        Author("shakunetsu", 5, commission = false, swap = false, interactiveQuest = false, moneyQuest = true),
        Author("минос", 5, commission = false, swap = true, interactiveQuest = true, moneyQuest = true),
        Author("c3rb3ru2", 6, commission = false, swap = true, interactiveQuest = false, moneyQuest = true),
        Author("kirivetika", 6, commission =false, swap = true, interactiveQuest = false, moneyQuest = true),
        Author("Маря", 7, commission = true, swap = false, interactiveQuest = false , moneyQuest = true),
        Author("XINSHI", 7, commission = false, swap = true, interactiveQuest = false, moneyQuest = true),
        Author("LIPEKA", 8, commission = false, swap = true, interactiveQuest = false, moneyQuest = false),
        Author("Крапива", 9, commission = false, swap = true, interactiveQuest = false, moneyQuest = true),
        Author("Орех", 9, commission = false, swap = true, interactiveQuest = false, moneyQuest = false),
        Author("Shugar`ok", 10, commission = false, swap = true, interactiveQuest = true, moneyQuest = false),
        Author("Kwadzimodo", 10, commission = false, swap = true, interactiveQuest = false, moneyQuest = true),
        Author("AIANO", 11, commission = false, swap = false, interactiveQuest = false, moneyQuest = true),
        Author("vacuuten", 11, commission = false, swap = true, interactiveQuest = false, moneyQuest = true),
        Author("tyunta", 12, commission = false, swap = true, interactiveQuest = false, moneyQuest = false),
        Author("XXARTL", 12, commission = false, swap = false, interactiveQuest = false, moneyQuest = false),
        Author("DEAD VANYA", 13, commission = false, swap = false, interactiveQuest = false, moneyQuest = true),
        Author("пилз", 13, commission = false, swap = true, interactiveQuest = false, moneyQuest = true),
        Author("Dexil", 14, commission = false, swap = true, interactiveQuest = false, moneyQuest = true),
        Author("korobka krodetsya", 14, commission = true, swap = true, interactiveQuest = false, moneyQuest = false),
        Author("Каята", 15, commission = false, swap = true, interactiveQuest = false, moneyQuest = true),
        Author("Katy-Tan", 16, commission = false, swap = true, interactiveQuest = false, moneyQuest = true),
        Author("Leone`s bones", 16, commission = false, swap = false, interactiveQuest = false, moneyQuest = true),
        Author("KIRASSOM", 17, commission = false, swap = true, interactiveQuest = false, moneyQuest = true),
        Author("aquariuzz", 17,commission = true, swap = true, interactiveQuest = false, moneyQuest = true),
        Author("kilka_got_high", 18, commission = false, swap = true, interactiveQuest = false, moneyQuest = true),
        Author("шилс орнот", 18, commission = false, swap = true, interactiveQuest = true, moneyQuest = true),
        Author("ASTER", 19, commission = false, swap = true, interactiveQuest = false, moneyQuest = true),
        Author("anilopa", 19, commission = false, swap = true, interactiveQuest = false, moneyQuest = true),
        Author("Монлиро", 20, commission = true, swap = true, interactiveQuest = false, moneyQuest = false),
        Author("Паровозик", 20, commission = true, swap = true, interactiveQuest = true, moneyQuest = true),
        Author("h_tch", 21, commission = false, swap = true, interactiveQuest = false, moneyQuest = true),
        Author("farshioli", 21, commission = false, swap = true, interactiveQuest = false, moneyQuest = true),
        Author("tjnewton", 22, commission = false, swap = true, interactiveQuest = false, moneyQuest = true),
        Author("VOLOKITA", 22, commission = false, swap = true, interactiveQuest = false, moneyQuest = true),
        Author("Swoops", 23, commission = false, swap = true, interactiveQuest = false, moneyQuest = true),
        Author("franklyshane", 23, commission = false, swap = true, interactiveQuest = false, moneyQuest = false),
        Author("Miel", 24, commission = true, swap = true, interactiveQuest = false, moneyQuest = true),
        Author("tobionart", 24, commission = false, swap = true, interactiveQuest = false, moneyQuest = true),
        Author("ленори", 25, commission = false, swap = true, interactiveQuest = false, moneyQuest = false),
        Author("Nyaftul kitten art", 25, commission = false, swap = false, interactiveQuest = false, moneyQuest = true),
        Author("кацузавр", 26, commission = false, swap = false, interactiveQuest = false, moneyQuest = false),
        Author("эричян", 27, commission = true, swap = false, interactiveQuest = false, moneyQuest = true),
        Author("sailorri", 28, commission = false, swap = false, interactiveQuest = false, moneyQuest = false),
        Author("Pupok", 28, commission = false, swap = true, interactiveQuest = false, moneyQuest = true),
        Author("Shade GDI", 29, commission = false, swap = true, interactiveQuest = false, moneyQuest = true),
        Author("FREAKY-PINKY", 29, commission = true, swap = true, interactiveQuest = false, moneyQuest = true),
        Author("твое солнышко", 30, commission = false, swap = false, interactiveQuest = false, moneyQuest = true),
        Author("vezar", 30, commission = false, swap = true, interactiveQuest = false, moneyQuest = true),
        Author("ENIJOI", 31, commission = false, swap = true, interactiveQuest = false, moneyQuest = true),
        Author("умио", 31, commission = false, swap = true, interactiveQuest = true, moneyQuest = true),
        Author("nostuk", 32, commission = false, swap = true, interactiveQuest = false, moneyQuest = false),
        Author("lemore", 32, commission = true, swap = true, interactiveQuest = false, moneyQuest = true),
        Author("nyeft", 33, commission = false, swap = false, interactiveQuest = false, moneyQuest = true),
        Author("Киотян", 33, commission = true, swap = true, interactiveQuest = false, moneyQuest = true)
    )

}