package com.example.razryadapi.filter

import com.example.razryadapi.R

val authors = listOf(
        Author("Kusweet", 1, commission = false, swap = true, interactiveQuest = false, moneyQuest = true,(R.drawable.kusweet), kusweet_fandoms, image_kysweet),
        Author("Cherseryy", 1, commission = false, swap = true, interactiveQuest = false, moneyQuest = true,(R.drawable.chersery),  cherseryy_fandoms, image_nocart),
        Author("Iris", 2, commission = false, swap = true, interactiveQuest = true, moneyQuest = true,(R.drawable.iris), Iris_fandoms, image_iris),
        Author("Demi", 2, commission = false, swap = true, interactiveQuest = false, moneyQuest = true,(R.drawable.demi), Demi_fandoms, image_Demi),
        Author("BRIT/0.5", 3, commission = false, swap = true, interactiveQuest = false, moneyQuest = true,(R.drawable.brit), BRIT_fandoms, image_brit),
        Author("Gosuto", 3, commission = true, swap = true, interactiveQuest = false, moneyQuest = true,(R.drawable.gosuto),Gosuto_fandoms, image_nocart),
        Author("Vhka", 4, commission = false, swap = true, interactiveQuest = true, moneyQuest = true,(R.drawable.vnka), Vhka_fandoms, image_vnka),
        Author("Mag", 4, commission = false, swap = false, interactiveQuest = false, moneyQuest = true,(R.drawable.mag), Mag_fandoms,images_mag),
        Author("Shakunetsu", 5, commission = false, swap = false, interactiveQuest = false, moneyQuest = true,(R.drawable.iris),Shakunetsu_fandoms, image_shakunetsu),
        Author("Минос", 5, commission = false, swap = true, interactiveQuest = true, moneyQuest = true,(R.drawable.minos), Minos_fandoms, image_minos),
        Author("C3rb3ru2", 6, commission = false, swap = true, interactiveQuest = false, moneyQuest = true,(R.drawable.c3rb3ru2), C3rb3ru2_fandoms, image_c3rb3ru2),
        Author("kirivetika", 6, commission =false, swap = false, interactiveQuest = false, moneyQuest = true,(R.drawable.krivetika), kirivetika_fandoms, image_kirivetika),
        Author("Маря", 7, commission = true, swap = false, interactiveQuest = false , moneyQuest = true,(R.drawable.marya), marya_fandoms, image_marya),
        Author("XINSHI", 7, commission = false, swap = true, interactiveQuest = false, moneyQuest = true,(R.drawable.xinshi), XINSHI_fandoms, image_nocart),
        Author("LIPEKA", 8, commission = false, swap = true, interactiveQuest = false, moneyQuest = false,(R.drawable.iris), LIPEKA_fandoms, image_lipeka),
        Author("Крапива", 9, commission = false, swap = true, interactiveQuest = false, moneyQuest = true,(R.drawable.lipeka), krapiva_fandoms, image_krapiva),
        Author("Орех", 9, commission = false, swap = true, interactiveQuest = false, moneyQuest = false,(R.drawable.oreh), oreh_fandoms, image_oreh),
        Author("Shugar`ok", 10, commission = false, swap = true, interactiveQuest = true, moneyQuest = false,(R.drawable.shugarok), Shugar_or_fandoms, image_sugar_ok),
        Author("Kwadzimodo", 10, commission = false, swap = true, interactiveQuest = false, moneyQuest = true, (R.drawable.kwadzimodo), Kwadzimodo_fandoms, image_kwadzimodo),
        Author("AIANO", 11, commission = false, swap = false, interactiveQuest = false, moneyQuest = true,(R.drawable.aiano), AIANO_fandoms, image_aino),
        Author("✷Vacuuten✷", 11, commission = false, swap = true, interactiveQuest = false, moneyQuest = true,(R.drawable.vacuuten), Vacuuten_fandoms, image_vacuuten),
        Author("Тюнтя", 12, commission = false, swap = true, interactiveQuest = false, moneyQuest = false,(R.drawable.tyntia), tyntia_fandoms, image_tunta),
        Author("XXARTL", 12, commission = false, swap = false, interactiveQuest = false, moneyQuest = false,(R.drawable.xxartl), XXARTL_fandoms, image_xxartl),
        Author("DEAD VANYA", 13, commission = false, swap = false, interactiveQuest = false, moneyQuest = true,(R.drawable.dead_vanya), DEAD_VANYA_fandoms, image_dead_v),
        Author("Пилз", 13, commission = false, swap = true, interactiveQuest = false, moneyQuest = true,(R.drawable.pilz), Pilz_fandoms, image_pilz ),
        Author("Dexil", 14, commission = false, swap = true, interactiveQuest = false, moneyQuest = true,(R.drawable.dexil), Dexil_fandoms, image_Dexil),
        Author("Korobka krodetsya", 14, commission = true, swap = true, interactiveQuest = false, moneyQuest = true,(R.drawable.korobka_krodetsya), Korobka_krodetsya_fandoms, image_korobka),
        Author("Каята", 15, commission = false, swap = true, interactiveQuest = false, moneyQuest = true,(R.drawable.kayata), kayata_fandoms, image_kayata),
        Author("Katy-Tan", 16, commission = false, swap = true, interactiveQuest = false, moneyQuest = true,(R.drawable.katy_tan), Katy_fandoms, image_katy),
        Author("Leone`s bones", 16, commission = false, swap = false, interactiveQuest = false, moneyQuest = true,(R.drawable.leones_bones), Leone_fandoms, image_leone),
        Author("KIRASSOM", 17, commission = false, swap = true, interactiveQuest = false, moneyQuest = true,(R.drawable.kirassom), KIRASSOM_fandoms, image_KIRASSOM),
        Author("Aquariuzz", 17,commission = true, swap = true, interactiveQuest = false, moneyQuest = true,(R.drawable.aquariuzz), Aquariuzz_fandoms, image_aquariuzz),
        Author("Kilka_got_high", 18, commission = false, swap = true, interactiveQuest = false, moneyQuest = true,(R.drawable.kilka), Kilka_fandoms, image_kilka),
        Author("Шилс орнот", 18, commission = false, swap = true, interactiveQuest = true, moneyQuest = true,(R.drawable.shils), shils_fandoms, image_shils),
        Author("ASTER", 19, commission = false, swap = true, interactiveQuest = false, moneyQuest = true,(R.drawable.aster), ASTER_fandoms, image_aster),
        Author("Anilopa", 19, commission = false, swap = true, interactiveQuest = false, moneyQuest = true,(R.drawable.anilopa), Anilopa_fandoms, image_anilopa),
        Author("Монлиро", 20, commission = true, swap = true, interactiveQuest = false, moneyQuest = false,(R.drawable.monliro), monliro_fandoms, images_monliro),
        Author("Паровозик", 20, commission = true, swap = true, interactiveQuest = true, moneyQuest = true,(R.drawable.paravosik),paravosik_fandoms, image_paravosik),
        Author("H_tch", 21, commission = false, swap = true, interactiveQuest = false, moneyQuest = true,(R.drawable.h_tch), H_tch_fandoms, image_h_tch),
        Author("Farshioli", 21, commission = false, swap = true, interactiveQuest = false, moneyQuest = true,(R.drawable.farshioli), Farshioli_fandoms, image_farshioli),
        Author("Tjnewton", 22, commission = false, swap = true, interactiveQuest = false, moneyQuest = true,(R.drawable.tjnewton), Tjnewton_fandoms, image_tjnewton),
        Author("VOLOKITA", 22, commission = false, swap = true, interactiveQuest = false, moneyQuest = true,(R.drawable.volokita), VOLOKITA_fandoms, image_volokita),
        Author("Swoops", 23, commission = false, swap = true, interactiveQuest = false, moneyQuest = true,(R.drawable.swoops), Swoops_fandoms, image_swoops),
        Author("Franklyshane", 23, commission = false, swap = true, interactiveQuest = false, moneyQuest = false,(R.drawable.franklyshane), Franklyshane_fandoms, image_franklyshane),
        Author("Miel", 24, commission = true, swap = true, interactiveQuest = false, moneyQuest = true,(R.drawable.miel), Miel_fandoms, image_miel),
        Author("Tobionart", 24, commission = false, swap = true, interactiveQuest = false, moneyQuest = true,(R.drawable.tobionart), Tobionart_fandoms, image_tobionart),
        Author("Ленори", 25, commission = false, swap = true, interactiveQuest = false, moneyQuest = false,(R.drawable.lenori), lenori_fandoms, image_lenori),
        Author("Nyaftul kitten art", 25, commission = false, swap = false, interactiveQuest = false, moneyQuest = true,(R.drawable.nyaft), Nyaftul_fandoms, image_nyaftul_kitten),
        Author("Кацузавр", 26, commission = false, swap = false, interactiveQuest = false, moneyQuest = false,(R.drawable.kazyzavr), zavr_fandoms, image_kazyzaur),
        Author("Эричян", 27, commission = true, swap = false, interactiveQuest = false, moneyQuest = true,(R.drawable.ary), Ary_fandoms, image_nocart),
        Author("Sailorri", 28, commission = false, swap = false, interactiveQuest = false, moneyQuest = false,(R.drawable.sailori), Sailorri_fandoms, images_sailorri),
        Author("Pupok", 28, commission = false, swap = true, interactiveQuest = false, moneyQuest = true,(R.drawable.pupok), Pupok_fandoms, image_Pupok),
        Author("Shade GDI", 29, commission = false, swap = true, interactiveQuest = false, moneyQuest = true,(R.drawable.shade), Shade_fandoms, image_shade),
        Author("FREAKY-PINKY", 29, commission = true, swap = true, interactiveQuest = false, moneyQuest = true,(R.drawable.freaky), FREAKY_fandoms, images_FREAKY),
        Author("Твое солнышко", 30, commission = true, swap = false, interactiveQuest = false, moneyQuest = true,(R.drawable.sunny), your_sunny_fandoms, image_your_sunny),
        Author("Vezar", 30, commission = false, swap = true, interactiveQuest = false, moneyQuest = true,(R.drawable.vezar), Vezar_fandoms, image_vezar),
        Author("ENIJOI", 31, commission = false, swap = true, interactiveQuest = false, moneyQuest = true,(R.drawable.enijoi), ENIJOI_fandoms, image_nocart),
        Author("Умио", 31, commission = false, swap = true, interactiveQuest = true, moneyQuest = true,(R.drawable.umio), Umio_fandoms, image_nocart),
        Author("Nostuk", 32, commission = false, swap = true, interactiveQuest = false, moneyQuest = false,(R.drawable.nostuk), Nostuk_fandoms, image_nocart),
        Author("Lemore", 32, commission = true, swap = true, interactiveQuest = false, moneyQuest = true,(R.drawable.lemore), Lemore_fandoms, image_lemore),
        Author("Nyeft", 33, commission = false, swap = false, interactiveQuest = false, moneyQuest = true,(R.drawable.nyaft), Nyeft_fandoms, images_Nyeft),
        Author("Киотян", 33, commission = true, swap = true, interactiveQuest = false, moneyQuest = true,(R.drawable.kyo),kio_fandoms, image_kyo)
)
